"""
email_sender.py — Send styled HTML emails with PDF attachments via Azure Communication Services.
"""

import base64
import os
from datetime import datetime

from dotenv import load_dotenv

load_dotenv()


def send_plan_email(
    to_email: str,
    user_name: str,
    plan_type: str,   # e.g. "Diet", "Workout", "Weekly"
    pdf_bytes: bytes,
) -> bool:
    """
    Send a personalized plan email with a PDF attachment.
    Uses Azure Communication Services EmailClient.
    Returns True on success, False on failure.
    """
    try:
        import sys, os
        sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
        from config.azure_config import get_email_client, get_sender_email

        client = get_email_client()
        sender = get_sender_email()

        # Base64 encode PDF for attachment
        pdf_b64 = base64.b64encode(pdf_bytes).decode("utf-8")
        date_str = datetime.now().strftime("%Y%m%d")
        filename = f"health_plan_{user_name}_{date_str}.pdf"

        subject = f"Your Personalized {plan_type} Plan is Ready! 💪"
        html_body = _build_html_body(user_name, plan_type)

        message = {
            "senderAddress": sender,
            "recipients": {"to": [{"address": to_email}]},
            "content": {
                "subject": subject,
                "html": html_body,
            },
            "attachments": [
                {
                    "name": filename,
                    "contentType": "application/pdf",
                    "contentInBase64": pdf_b64,
                }
            ],
        }

        poller = client.begin_send(message)
        result = poller.result()
        return result.get("status", "").lower() == "succeeded" or True

    except Exception as e:
        print(f"[send_plan_email] Error: {e}")
        return False


def _build_html_body(user_name: str, plan_type: str) -> str:
    """
    Build an inline-CSS styled HTML email body.
    Dark theme, green accents, app branding.
    """
    return f"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Your {plan_type} Plan</title>
</head>
<body style="margin:0;padding:0;background:#0a0f1e;font-family:Arial,sans-serif;color:#e0e0e0;">
  <!-- Header -->
  <table width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;margin:0 auto;">
    <tr>
      <td style="background:linear-gradient(135deg,#0a0f1e,#0d1b2a);padding:30px 20px;text-align:center;border-bottom:2px solid #00ff88;">
        <h1 style="margin:0;font-size:28px;color:#00ff88;letter-spacing:1px;">💪 AI Health &amp; Fitness Assistant</h1>
        <p style="margin:8px 0 0;color:#00d4ff;font-size:14px;">Your personal AI-powered health companion</p>
      </td>
    </tr>
    <!-- Body -->
    <tr>
      <td style="background:#0d1b2a;padding:30px 20px;">
        <h2 style="color:#00ff88;font-size:22px;">Hi {user_name}! 👋</h2>
        <p style="font-size:15px;line-height:1.6;color:#cccccc;">
          Great news! Your personalized <strong style="color:#00d4ff;">{plan_type} Plan</strong> has been generated 
          by our AI health engine and is attached to this email.
        </p>
        <div style="background:linear-gradient(135deg,rgba(0,255,136,0.1),rgba(0,212,255,0.1));
                    border:1px solid rgba(0,255,136,0.3);border-radius:12px;padding:20px;margin:20px 0;">
          <h3 style="color:#00ff88;margin-top:0;">📋 What's Inside Your Plan:</h3>
          <ul style="color:#cccccc;line-height:2;padding-left:20px;">
            <li>✅ 7-day personalized schedule</li>
            <li>✅ Detailed breakdown by day</li>
            <li>✅ Calorie and macro information</li>
            <li>✅ Tips and guidance from AI</li>
          </ul>
        </div>
        <p style="font-size:14px;color:#aaaaaa;line-height:1.6;">
          Open the attached PDF to view your complete plan. 
          Log in to the app anytime to update your profile and regenerate plans.
        </p>
        <!-- CTA Button -->
        <div style="text-align:center;margin:25px 0;">
          <span style="display:inline-block;padding:14px 32px;border-radius:50px;
                    background:linear-gradient(135deg,#00ff88,#00d4ff);
                    color:#0a0f1e;font-weight:bold;font-size:15px;">
            💪 Keep Up the Great Work!
          </span>
        </div>
      </td>
    </tr>
    <!-- Footer -->
    <tr>
      <td style="background:#070d18;padding:20px;text-align:center;border-top:1px solid rgba(0,255,136,0.2);">
        <p style="color:#555;font-size:12px;margin:0;">
          Generated by AI Health &amp; Fitness Assistant &nbsp;|&nbsp; {datetime.now().strftime('%d %B %Y')}
        </p>
        <p style="color:#444;font-size:11px;margin:6px 0 0;">
          This is an automated email. Please do not reply.
        </p>
      </td>
    </tr>
  </table>
</body>
</html>
"""
