"""
pdf_generator.py — Generate styled PDF reports using ReportLab.
Supports diet plans, workout plans, and weekly summary reports.
Returns PDF as bytes for download or email attachment.
"""

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    HRFlowable,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT

# ── Brand colours ─────────────────────────────────────
NAVY = colors.HexColor("#0a0f1e")
DARK_BLUE = colors.HexColor("#0d1b2a")
GREEN = colors.HexColor("#00ff88")
CYAN = colors.HexColor("#00d4ff")
WHITE = colors.white
LIGHT_GRAY = colors.HexColor("#e0e0e0")
AMBER = colors.HexColor("#ffaa00")


def _build_styles():
    """Build and return a dict of named paragraph styles."""
    styles = getSampleStyleSheet()
    custom = {
        "title": ParagraphStyle(
            "title",
            parent=styles["Title"],
            fontSize=24,
            textColor=GREEN,
            alignment=TA_CENTER,
            spaceAfter=6,
        ),
        "subtitle": ParagraphStyle(
            "subtitle",
            parent=styles["Normal"],
            fontSize=13,
            textColor=CYAN,
            alignment=TA_CENTER,
            spaceAfter=12,
        ),
        "section_header": ParagraphStyle(
            "section_header",
            parent=styles["Heading2"],
            fontSize=14,
            textColor=GREEN,
            spaceBefore=14,
            spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "body",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.black,
            spaceAfter=4,
        ),
        "cell_body": ParagraphStyle(
            "cell_body",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.black,
            alignment=TA_LEFT,
            wordWrap="CJK",
        ),
        "footer": ParagraphStyle(
            "footer",
            parent=styles["Normal"],
            fontSize=8,
            textColor=colors.gray,
            alignment=TA_CENTER,
        ),
    }
    return custom


def _header_footer(canvas, doc):
    """Draw header/footer on every page."""
    canvas.saveState()
    width, height = A4
    # Header bar
    canvas.setFillColor(NAVY)
    canvas.rect(0, height - 1.5 * cm, width, 1.5 * cm, fill=True, stroke=False)
    canvas.setFillColor(GREEN)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawCentredString(width / 2, height - 1.0 * cm, "💪 AI Health & Fitness Assistant")
    # Footer
    canvas.setFillColor(colors.gray)
    canvas.setFont("Helvetica", 8)
    canvas.drawCentredString(
        width / 2,
        0.6 * cm,
        f"Generated by AI Health & Fitness Assistant  |  {datetime.now().strftime('%d %b %Y')}  |  Page {doc.page}",
    )
    canvas.restoreState()


def _table_style(header_bg=NAVY, alt_bg=colors.HexColor("#f0f8f4")):
    """Return a standard TableStyle for report tables."""
    return TableStyle(
        [
            ("BACKGROUND", (0, 0), (-1, 0), header_bg),
            ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, alt_bg]),
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]
    )


# ─────────────────────────────────────────────
# DIET PLAN PDF
# ─────────────────────────────────────────────
def generate_diet_plan_pdf(user_profile: dict, diet_plan: dict) -> bytes:
    """
    Generate a styled PDF for the 7-day diet plan.
    Returns PDF as bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=2 * cm,
        bottomMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
    )
    styles = _build_styles()
    story = []

    # Cover
    story.append(Spacer(1, 1 * cm))
    story.append(Paragraph("🥗 Personalized 7-Day Diet Plan", styles["title"]))
    story.append(
        Paragraph(
            f"Prepared for: <b>{user_profile.get('name', 'User')}</b>  |  Goal: {user_profile.get('goal', 'N/A')}",
            styles["subtitle"],
        )
    )
    story.append(HRFlowable(width="100%", thickness=1, color=GREEN, spaceAfter=12))

    # BMI info
    bmi = user_profile.get("bmi", "N/A")
    story.append(
        Paragraph(f"BMI: <b>{bmi}</b>  |  Daily Calorie Target: <b>{user_profile.get('daily_calories', 2000)} kcal</b>", styles["body"])
    )
    story.append(Spacer(1, 0.5 * cm))

    days_data = diet_plan.get("days", diet_plan) if isinstance(diet_plan, dict) else {}

    for day_key, day_meals in days_data.items():
        story.append(Paragraph(f"📅 {day_key}", styles["section_header"]))
        table_data = [["Meal", "Food Items", "Calories", "Protein (g)", "Carbs (g)", "Fats (g)"]]
        if isinstance(day_meals, dict):
            for meal_name, meal_info in day_meals.items():
                if isinstance(meal_info, dict):
                    food_items_text = meal_info.get("items", meal_info.get("food_items", ""))
                    row = [
                        meal_name,
                        Paragraph(str(food_items_text), styles["cell_body"]),
                        str(meal_info.get("calories", "")),
                        str(meal_info.get("protein", meal_info.get("protein_g", ""))),
                        str(meal_info.get("carbs", meal_info.get("carbs_g", ""))),
                        str(meal_info.get("fats", meal_info.get("fats_g", ""))),
                    ]
                    table_data.append(row)
        t = Table(table_data, colWidths=[1.2*inch, 3.8*inch, 0.8*inch, 0.8*inch, 0.8*inch, 0.8*inch])
        t.setStyle(_table_style())
        story.append(t)
        story.append(Spacer(1, 0.3 * cm))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buffer.getvalue()


# ─────────────────────────────────────────────
# WORKOUT PLAN PDF
# ─────────────────────────────────────────────
def generate_workout_plan_pdf(user_profile: dict, workout_plan: dict) -> bytes:
    """
    Generate a styled PDF for the 7-day workout plan.
    Returns PDF as bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=2 * cm,
        bottomMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
    )
    styles = _build_styles()
    story = []

    story.append(Spacer(1, 1 * cm))
    story.append(Paragraph("🏋️ Personalized 7-Day Workout Plan", styles["title"]))
    story.append(
        Paragraph(
            f"Prepared for: <b>{user_profile.get('name', 'User')}</b>  |  Goal: {user_profile.get('goal', 'N/A')}  |  Level: {user_profile.get('activity_level', 'N/A')}",
            styles["subtitle"],
        )
    )
    story.append(HRFlowable(width="100%", thickness=1, color=GREEN, spaceAfter=12))

    days_data = workout_plan.get("days", workout_plan) if isinstance(workout_plan, dict) else {}

    for day_key, day_info in days_data.items():
        story.append(Paragraph(f"📅 {day_key}", styles["section_header"]))
        if isinstance(day_info, dict) and day_info.get("rest_day"):
            story.append(Paragraph("😴 Rest Day — Focus on recovery and hydration.", styles["body"]))
        else:
            exercises = day_info.get("exercises", []) if isinstance(day_info, dict) else []
            table_data = [["Exercise", "Sets", "Reps", "Rest", "Muscle Group", "Calories"]]
            for ex in exercises:
                if isinstance(ex, dict):
                    exercise_name = ex.get("name", "")
                    table_data.append([
                        Paragraph(str(exercise_name), styles["cell_body"]),
                        str(ex.get("sets", "")),
                        str(ex.get("reps", "")),
                        ex.get("rest", ""),
                        ex.get("muscle_group", ""),
                        str(ex.get("calories_burned", "")),
                    ])
            if len(table_data) > 1:
                t = Table(table_data, colWidths=[2.5*inch, 0.7*inch, 0.7*inch, 0.9*inch, 1.5*inch, 0.8*inch])
                t.setStyle(_table_style())
                story.append(t)
        story.append(Spacer(1, 0.3 * cm))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buffer.getvalue()


# ─────────────────────────────────────────────
# WEEKLY REPORT PDF
# ─────────────────────────────────────────────
def generate_weekly_report_pdf(user_profile: dict, report: dict) -> bytes:
    """
    Generate a styled PDF for the weekly health report.
    Returns PDF as bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=2 * cm,
        bottomMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
    )
    styles = _build_styles()
    story = []

    story.append(Spacer(1, 1 * cm))
    story.append(Paragraph("📊 Weekly Health & Fitness Report", styles["title"]))
    story.append(
        Paragraph(
            f"User: <b>{user_profile.get('name', 'User')}</b>  |  Week ending: {datetime.now().strftime('%d %b %Y')}",
            styles["subtitle"],
        )
    )
    story.append(HRFlowable(width="100%", thickness=1, color=GREEN, spaceAfter=12))

    # Performance Score
    score = report.get("performance_score", "N/A")
    story.append(Paragraph(f"🏆 Overall Performance Score: <b>{score} / 100</b>", styles["section_header"]))
    story.append(Spacer(1, 0.3 * cm))

    # Achievements
    story.append(Paragraph("✅ Top Achievements", styles["section_header"]))
    for ach in report.get("achievements", []):
        story.append(Paragraph(f"• {ach}", styles["body"]))
    story.append(Spacer(1, 0.3 * cm))

    # Areas to Improve
    story.append(Paragraph("⚠️ Areas to Improve", styles["section_header"]))
    for imp in report.get("improvements", []):
        story.append(Paragraph(f"• {imp}", styles["body"]))
    story.append(Spacer(1, 0.3 * cm))

    # Personalized Advice
    story.append(Paragraph("💡 Personalized Advice for Next Week", styles["section_header"]))
    advice = report.get("advice", "")
    story.append(Paragraph(advice, styles["body"]))
    story.append(Spacer(1, 0.3 * cm))

    # Motivational Message
    story.append(Paragraph("🌟 Motivational Message", styles["section_header"]))
    motivation = report.get("motivational_message", "Keep going — every step counts!")
    story.append(Paragraph(f"<i>{motivation}</i>", styles["body"]))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buffer.getvalue()
